function ship_export_script(cfg, fileName)
%SHIP_EXPORT_SCRIPT Export the current GUI configuration as runnable code.

[cfg, ~] = ship_validate_config(cfg);
[folder, name, ext] = fileparts(fileName);
if isempty(ext)
    ext = '.m';
end
if isempty(folder)
    folder = pwd;
end
fileName = fullfile(folder, [name, ext]);

fid = fopen(fileName, 'w', 'n', 'UTF-8');
if fid < 0
    error('ship:FileWrite', 'Cannot write file: %s', fileName);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '%% Generated by ship_control_app on %s\n', char(datetime('now')));
fprintf(fid, '%% Edit any value below, then run this file.\n\n');
helperFolder = strrep(fileparts(mfilename('fullpath')), '''', '''''');
fprintf(fid, '%% Helper functions used by this generated runner:\n');
fprintf(fid, 'addpath(''%s'');\n\n', helperFolder);
fprintf(fid, 'cfg = ship_default_config();\n');

writeNumber('cfg.radar.fc', cfg.radar.fc);
writeNumber('cfg.radar.pulseWidth', cfg.radar.pulseWidth);
writeNumber('cfg.radar.bandwidth', cfg.radar.bandwidth);
writeNumber('cfg.radar.lookAngleDeg', cfg.radar.lookAngleDeg);
writeNumber('cfg.radar.altitude', cfg.radar.altitude);
writeNumber('cfg.radar.velocity', cfg.radar.velocity);
writeNumber('cfg.scene.centerAzimuth', cfg.scene.centerAzimuth);
writeNumber('cfg.scene.azimuthSpan', cfg.scene.azimuthSpan);
writeNumber('cfg.scene.rangeSpan', cfg.scene.rangeSpan);
writeNumber('cfg.scene.scale', cfg.scene.scale);
writeNumber('cfg.target.pointSpacing', cfg.target.pointSpacing);
writeNumber('cfg.target.pointsPerDot', cfg.target.pointsPerDot);
writeNumber('cfg.target.dotRadius', cfg.target.dotRadius);
writeNumber('cfg.target.amplitude', cfg.target.amplitude);
writeNumber('cfg.target.randomSeed', cfg.target.randomSeed);
writeNumber('cfg.target.downsampleRate', cfg.target.downsampleRate);
writeNumber('cfg.coverage.azimuthHalfWidth', cfg.coverage.azimuthHalfWidth);
writeNumber('cfg.coverage.rangeHalfWidth', cfg.coverage.rangeHalfWidth);

for k = 1:4
    s = cfg.metasurfaces(k);
    safeName = strrep(s.name, '''', '''''');
    fprintf(fid, 'cfg.metasurfaces(%d).name = ''%s'';\n', k, safeName);
    fprintf(fid, 'cfg.metasurfaces(%d).enabled = %s;\n', k, mat2str(logical(s.enabled)));
    fprintf(fid, 'cfg.metasurfaces(%d).azimuth = %.17g;\n', k, s.azimuth);
    fprintf(fid, 'cfg.metasurfaces(%d).range = %.17g;\n', k, s.range);
    fprintf(fid, 'cfg.metasurfaces(%d).slowPiCount = %d;\n', k, s.slowPiCount);
    fprintf(fid, 'cfg.metasurfaces(%d).slowZeroCount = %d;\n', k, s.slowZeroCount);
    fprintf(fid, 'cfg.metasurfaces(%d).fastPhaseCode = %s;\n', k, mat2str(s.fastPhaseCode, 17));
    fprintf(fid, 'cfg.metasurfaces(%d).fastRepeats = %d;\n', k, s.fastRepeats);
end

fprintf(fid, 'cfg.sampling.mode = ''%s'';\n', cfg.sampling.mode);
writeNumber('cfg.sampling.azimuthSamples', cfg.sampling.azimuthSamples);
writeNumber('cfg.sampling.rangeSamples', cfg.sampling.rangeSamples);
writeNumber('cfg.execution.maxMemoryGB', cfg.execution.maxMemoryGB);
writeNumber('cfg.display.dynamicRangeDB', cfg.display.dynamicRangeDB);
writeNumber('cfg.display.gamma', cfg.display.gamma);

fprintf(fid, '\n[~, estimate] = ship_validate_config(cfg);\n');
fprintf(fid, 'fprintf(''Na=%%d, Nr=%%d, estimated memory=%%.2f GB\\n'', ...\n');
fprintf(fid, '    estimate.na, estimate.nr, estimate.estimatedMemoryGB);\n');
fprintf(fid, 'result = ship_run_simulation(cfg, @(p,msg) progress(p,msg));\n');
fprintf(fid, 'figure(''Color'',''w'');\n');
fprintf(fid, 'imagesc(result.rangeAxis, result.azimuthAxis, result.imageDB);\n');
fprintf(fid, 'set(gca, ''YDir'', ''normal''); axis image; colormap jet; colorbar;\n');
fprintf(fid, 'clim([-cfg.display.dynamicRangeDB, 0]);\n');
fprintf(fid, 'xlabel(''Range (m)''); ylabel(''Azimuth (m)''); title(''Four-metasurface RD image'');\n\n');
fprintf(fid, 'function keepGoing = progress(p, msg)\n');
fprintf(fid, 'fprintf(''[%%3.0f%%%%] %%s\\n'', 100*p, msg);\n');
fprintf(fid, 'keepGoing = true;\n');
fprintf(fid, 'end\n');

    function writeNumber(lhs, value)
        fprintf(fid, '%s = %.17g;\n', lhs, value);
    end
end
